# Generated by Django 5.0.6 on 2024-07-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='links',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='Profile.links'),
            preserve_default=False,
        ),
    ]
