# Generated by Django 5.0.6 on 2024-07-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_user_profile_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='links',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='Profile.links'),
        ),
    ]
