# Generated by Django 5.0.6 on 2024-07-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_remove_user_profile_links_links_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField()),
                ('loss', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('league', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='Profile.stats')),
            ],
        ),
        migrations.AddField(
            model_name='user_profile',
            name='stats',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Profile.stats'),
            preserve_default=False,
        ),
    ]
