# Generated by Django 5.0.6 on 2024-07-23 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_remove_user_profile_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Profile.stats'),
        ),
    ]
