# Generated by Django 5.0.6 on 2024-07-23 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_user_profile_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='stats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='Profile.stats'),
            preserve_default=False,
        ),
    ]
