# Generated by Django 5.0.6 on 2024-07-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_graph_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='stats',
        ),
    ]
