# Generated by Django 5.0.6 on 2024-07-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_remove_graph_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graph',
            new_name='Graphh',
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Statss',
        ),
    ]
