# Generated by Django 5.0.6 on 2024-07-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_rename_graph_graphh_rename_stats_statss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graphh',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='stats',
        ),
        migrations.DeleteModel(
            name='Statss',
        ),
    ]
