# Generated by Django 5.0.6 on 2024-07-23 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_stats_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='stats',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Profile.stats'),
            preserve_default=False,
        ),
    ]
