# Generated by Django 4.2.13 on 2024-07-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_member_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='id',
            new_name='Id',
        ),
    ]
