# Generated by Django 4.2.13 on 2024-07-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_rename_id_member_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Id',
            new_name='id',
        ),
    ]
