# Generated by Django 5.0.6 on 2024-07-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('ROUND_16', 'Round of 16'), ('QUARTERFINALS', 'Quarterfinals'), ('SEMIFINALS', 'Semifinals'), ('FINAL', 'Final')], max_length=20)),
                ('date', models.DateField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournament.tournament')),
            ],
        ),
    ]
