# Generated by Django 5.0.6 on 2024-07-26 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0004_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='Tournament.tournament'),
        ),
    ]
