# Generated by Django 5.0.6 on 2024-07-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0005_alter_stage_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='num_players',
            field=models.IntegerField(choices=[(4, '4 Players'), (8, '8 Players'), (16, '16 Players')]),
        ),
    ]
