# Generated by Django 5.0.6 on 2024-07-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0008_player_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='final_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='quarterfinals_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='round_of_16_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='semifinals_date',
        ),
        migrations.AddField(
            model_name='stage',
            name='ready_to_play',
            field=models.BooleanField(default=False),
        ),
    ]
