# Generated by Django 4.2.13 on 2024-07-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0009_remove_tournament_final_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='Tournament.stage'),
        ),
    ]
