# Generated by Django 4.2.13 on 2024-07-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament', '0010_alter_player_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
